name: in_app_purchase_storekit_example
description: Demonstrates how to use the in_app_purchase_storekit plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase_platform_interface:
    git:
      url: https://github.com/maxischubert93/plugins.git
      path: packages/in_app_purchase/in_app_purchase_platform_interface
      ref: new-billing-flow
  in_app_purchase_storekit:
    git:
      url: https://github.com/maxischubert93/plugins.git
      path: packages/in_app_purchase/in_app_purchase_storekit
      ref: new-billing-flow
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
